name: Comment on PR

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]
    branches:
      - main

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - name: Add a comment to the PR
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.WORKFLOW_API_TOKEN }}
        script: |
          const prNumber = context.payload.pull_request.number;
          const comment = "Thanks for the PR, we'll merge it after review.";
          await github.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: comment,
          });
